web/config/routes.rb
Rails.application.routes.draw do
  root to: 'home#show'
  get 'sign_in', to: 'sessions#new'
  get 'app_sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
end

web/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

web/app/models/google_auth.rb
class GoogleAuth
  class << self
    def verify(id_token)
      result = fetch_token_info(id_token)
      return nil if result.nil?

      result['name']
    end

    def fetch_token_info(token)
      validator = GoogleIDToken::Validator.new
      validator.check(token, '<YOUR OAUTH CLIENT ID HERE>')
    rescue GoogleIDToken::ValidationError => e
      Rails.logger.info("Failed to verify token, #{e}")
      nil
    end
  end
end

web/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  private

  def authenticate_user!
    @current_user_name = session[:current_user_name]
    if @current_user_name.blank?
      redirect_to sign_in_path, alert: 'Unauthorized'
    end
  end
end

web/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    name = GoogleAuth.verify(cookies.delete(:id_token))
    if name.present?
      session[:current_user_name] = name
      redirect_to root_path, notice: 'Signed in'
    else
      redirect_to sign_in_path
    end
  end

  def destroy
    session.delete(:current_user_name)
    redirect_to sign_in_path, notice: 'Signed out'
  end
end

web/app/helpers/application_helper.rb
module ApplicationHelper
end

web/app/views/home/show.html.erb
<div class="flex flex-col items-center w-full">
  <div>
    Hello, <span class="font-bold text-blue-400"><%= @current_user_name %></span>
  </div>
  <div class="mt-5">
    <%= button_to 'Sign out', sign_out_path, method: :delete, class: 'text-gray-600 text-sm underline' %>
  </div>
</div>

web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Web</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>